In [2]:
import numpy as np

In [5]:
ar=np.arange(0,10)

In [6]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
ar.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
a=[0, 1, 2, 3, 4]
b=[5, 6, 7, 8, 9]
c=[1, 1, 1, 1, 1]
d=[1, 1, 1, 1, 1]

In [11]:
np.vstack((a,b,c,d))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
x=[0, 1, 2, 3, 4, 1, 1, 1, 1, 1]
y=[5, 6, 7, 8, 9, 1, 1, 1, 1, 1]

In [14]:
xy=np.hstack((x,y))

In [16]:
xy.reshape(2,10)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [19]:
a=np.arange(0,14).reshape(2,7)

In [20]:
a

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13]])

In [24]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [25]:
b=np.arange(0,15)

In [26]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
b.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [37]:
arr=np.arange(25).reshape(5,5)

In [38]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [39]:
np.square(arr)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

In [35]:
np.square(arr)

array([[[[[  0,   1],
          [  4,   9]],

         [[ 16,  25],
          [ 36,  49]]],


        [[[ 64,  81],
          [100, 121]],

         [[144, 169],
          [196, 225]]]],



       [[[[256, 289],
          [324, 361]],

         [[400, 441],
          [484, 529]]],


        [[[576, 625],
          [676, 729]],

         [[784, 841],
          [900, 961]]]]], dtype=int32)

In [40]:
arr=np.arange(30).reshape(5,6)

In [41]:
arr.mean()

14.5

In [42]:
np.std(arr)

8.65544144839919

In [43]:
np.transpose(arr)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [44]:
arr=np.arange(16).reshape(4,4)

In [45]:
np.diag(arr)

array([ 0,  5, 10, 15])

In [46]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
np.diag(arr).sum()

30

In [50]:
np.linalg.det(arr)

-2.9582283945787796e-30

In [52]:
np.percentile(arr,5)

0.75

In [53]:
np.percentile(arr,95)

14.25

In [51]:
np.isnan(arr)#for find null values is array

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])