In [1]:
import numpy as np

In [7]:
np.empty(10)

array([6.23042070e-307, 7.56587584e-307, 1.37961302e-306, 6.23053614e-307,
       1.42419530e-306, 1.78021527e-306, 6.23059726e-307, 1.33511562e-306,
       6.89805151e-307, 1.11261909e-306])

In [2]:
np.arange(10,50,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [3]:
np.arange(10,50,1).shape    

(40,)

In [4]:
x=np.arange(10,50,1)


In [5]:
x.dtype

dtype('int32')

In [6]:
print(np.__version__)


1.16.5


In [7]:
print(np.show_config())


mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/anaconda\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/anaconda\\Library\\include']
blas_opt_in

In [8]:
x.ndim

1

In [12]:
y=np.ones(10, dtype=bool)

In [13]:
y

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [16]:
z=np.array((2,2),(2,2))

TypeError: data type not understood

In [18]:
z=np.arange(12).reshape(3,4)

In [19]:
z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
z3=np.arange(12).reshape(3,2,2)

In [21]:
z3

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [22]:
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [26]:
x[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [27]:
n=np.zeros(10)

In [28]:
n[4]=1

In [29]:
n

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [30]:
idt=np.ones(8).reshape(2,2,2)

In [31]:
idt

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [32]:
arr = np.array([1, 2, 3, 4, 5])

In [36]:
arr=arr.astype(float)

In [37]:
arr.dtype

dtype('float64')

In [38]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  

arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])


In [39]:
arr1.dot(arr2)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [40]:
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [41]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 

arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])

In [43]:
arr=np.greater(arr1,arr2)

In [47]:
a=arr1[arr]

In [48]:
arr=np.greater(arr2,arr1)

In [49]:
b=arr2[arr]

In [51]:
np.concatenate((a,b),axis=0)

array([ 1.,  3.,  5.,  4.,  7., 12.])

In [52]:
ar=np.arange(10)

In [53]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
ar[ar%2==1]

array([1, 3, 5, 7, 9])

In [55]:
ar[ar%2==1]=-1

In [56]:
ar

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [57]:
arr=np.arange(10)

In [61]:
arr[4:8]=12

In [62]:
arr

array([ 0,  1,  2,  3, 12, 12, 12, 12,  8,  9])

In [78]:
arr1=np.ones((4,4))

In [79]:
arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [80]:
arr1[1:-1,1:-1]=0

In [81]:
arr1

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [93]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])

In [97]:
arr2d[1][1]=12

In [98]:
arr2d.ndim


2

In [99]:
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [101]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [102]:
arr3d[:][0][0]=64

In [103]:
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [106]:
a=np.arange(10).reshape(2,5)

In [107]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [108]:
a.ndim




2

In [111]:
a[0::,2]

array([2, 7])

In [112]:
rarr=np.random.rand(10,10)

In [113]:
rarr

array([[0.56433973, 0.51872201, 0.6781543 , 0.5249753 , 0.88282551,
        0.43975131, 0.21742605, 0.14855424, 0.06284848, 0.99160465],
       [0.06097946, 0.49128901, 0.59625766, 0.25656569, 0.18287392,
        0.64167649, 0.95071823, 0.47946761, 0.89048759, 0.56838334],
       [0.62876734, 0.48780103, 0.55795692, 0.7018444 , 0.9943919 ,
        0.39321217, 0.16488155, 0.26115005, 0.99765745, 0.73487617],
       [0.1237121 , 0.46041697, 0.77319922, 0.03303035, 0.55070477,
        0.27330811, 0.39838498, 0.69653596, 0.13776382, 0.0193349 ],
       [0.33863199, 0.56928471, 0.81061456, 0.65292421, 0.81883417,
        0.44391283, 0.80468491, 0.34439901, 0.72749358, 0.77019742],
       [0.68401593, 0.61162194, 0.47722143, 0.36624067, 0.64563999,
        0.90631826, 0.95725596, 0.02808598, 0.3147034 , 0.12007353],
       [0.57822205, 0.19639566, 0.86092474, 0.38364121, 0.32723355,
        0.58690408, 0.22952677, 0.64021157, 0.20022061, 0.31160806],
       [0.43709497, 0.03251983, 0.6522404

In [118]:
mx=np.amax(rarr)

In [119]:
mx

0.9976574482889021

In [120]:
mn=np.amin(rarr)

In [121]:
mn


0.017799786553930108

In [123]:
a = np.array([1,2,3,2,3,4,3,4,5,6])

In [124]:
 b = np.array([7,2,10,2,7,4,9,4,9,8])

In [126]:
cm=np.intersect1d(a,b)

In [127]:
cm


array([2, 4])

In [128]:
a[cm]

array([3, 3])

In [129]:
np.nonzero(np.in1d(a,b))

(array([1, 3, 5, 7], dtype=int64),)

In [23]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [24]:
data = np.random.randn(7, 4)

In [25]:
data

array([[ 0.03653683, -0.3544091 ,  0.73192202,  0.22622139],
       [-1.00589983,  0.05758154,  0.13508137,  1.13199661],
       [-0.25373024, -1.66687339, -0.18634128,  0.96828715],
       [-0.18447084,  0.29120487,  0.80328372,  0.51996208],
       [ 0.25185189, -1.80363632,  0.1544748 , -0.64660279],
       [ 0.25065786,  0.33504963, -0.65713593, -0.29745472],
       [-0.94056974, -0.22659881,  0.57209051, -2.36142189]])

In [26]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [27]:
data[names!='Will']

array([[ 0.03653683, -0.3544091 ,  0.73192202,  0.22622139],
       [-1.00589983,  0.05758154,  0.13508137,  1.13199661],
       [-0.18447084,  0.29120487,  0.80328372,  0.51996208],
       [ 0.25065786,  0.33504963, -0.65713593, -0.29745472],
       [-0.94056974, -0.22659881,  0.57209051, -2.36142189]])

In [40]:
ms=(names!='Will')

In [41]:
ms

array([ True,  True, False,  True, False,  True,  True])

In [42]:
ns=(names!='Joe')

In [46]:
data[ms]

array([[ 0.03653683, -0.3544091 ,  0.73192202,  0.22622139],
       [-1.00589983,  0.05758154,  0.13508137,  1.13199661],
       [-0.18447084,  0.29120487,  0.80328372,  0.51996208],
       [ 0.25065786,  0.33504963, -0.65713593, -0.29745472],
       [-0.94056974, -0.22659881,  0.57209051, -2.36142189]])

In [47]:
data[ns]

array([[ 0.03653683, -0.3544091 ,  0.73192202,  0.22622139],
       [-0.25373024, -1.66687339, -0.18634128,  0.96828715],
       [-0.18447084,  0.29120487,  0.80328372,  0.51996208],
       [ 0.25185189, -1.80363632,  0.1544748 , -0.64660279]])

In [50]:
arr=np.arange(1,10)

In [52]:
arr=np.sqrt(arr)

In [53]:
arr

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [54]:
np.where(arr<=2,2,arr)

array([2.        , 2.        , 2.        , 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [55]:
ar1=np.random.rand(12)

In [56]:
ar1

array([0.75513498, 0.41107697, 0.43429619, 0.97229872, 0.44483854,
       0.60215263, 0.86068336, 0.46774463, 0.02133759, 0.69752176,
       0.38383725, 0.5255979 ])

In [57]:
ar2=np.random.rand(12)

In [58]:
np.maximum(ar1,ar2)

array([0.87065705, 0.41107697, 0.43429619, 0.97229872, 0.44483854,
       0.60215263, 0.93833016, 0.46774463, 0.89468218, 0.69752176,
       0.38383725, 0.54299772])

In [59]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [63]:
nnames=np.unique(names)

In [64]:
nnames


array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [65]:
nnames.sort()

In [66]:
nnames

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [92]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [97]:
c=np.setdiff1d(a,b)

In [98]:
c

array([1, 2, 3, 4])

In [76]:
sa=np.array([[34,43,73],[82,22,12],[53,94,66]])

In [77]:
sa

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [99]:
sa=np.delete(sa,1,axis=1)

In [100]:
sa

array([[34, 73],
       [82, 12],
       [53, 66]])

In [101]:
np.insert(sa,1,[10,10,10],axis=1)

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

In [84]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])


In [85]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [86]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [87]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [88]:
ra=np.random.rand(20)

In [89]:
ra.cumsum()

array([ 0.9409434 ,  1.42333973,  1.63798061,  2.39533943,  3.07966617,
        3.77265962,  3.98820391,  4.75509853,  5.05358038,  5.97229146,
        6.83176326,  7.25679779,  8.0790172 ,  8.85738591,  9.04965757,
        9.06006666, 10.0587271 , 10.24316805, 10.6330777 , 11.00799968])